#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

mkdir -p data
export PLANTGUARD_SERVER_ADDRESS="${PLANTGUARD_SERVER_ADDRESS:-:8080}"
export PLANTGUARD_DATABASE_DRIVER="${PLANTGUARD_DATABASE_DRIVER:-sqlite}"
export PLANTGUARD_DATABASE_DSN="${PLANTGUARD_DATABASE_DSN:-./data/plantguard.db}"
export PLANTGUARD_DATABASE_MIGRATIONS_DIR="${PLANTGUARD_DATABASE_MIGRATIONS_DIR:-./migrations/sqlite}"
export PLANTGUARD_LOGGING_FORMAT="${PLANTGUARD_LOGGING_FORMAT:-json}"
export PLANTGUARD_WORKER_INTERVAL="${PLANTGUARD_WORKER_INTERVAL:-15s}"

go run ./cmd/api
